### ISSUE TITLE
Decimal point

### ISSUE THREAD

**Issue by twoporylyj** [nikita9604/Scientific-Calculator-with-Keypad#1]
Greetings. How do I enter decimal point? # and * do nothing. Thanks.

**Comment by nikita9604** [comment]
Hello, the code is only designed to take input as a whole number. However, everything is displayed / represented in the form of float, to have accuracy upto 2 decimal places w.r.t the result computation.
You are encouraged to do further enhancements to the code to take decimal input using # and *. Currently that's not implemented.

**Comment by nikita9604** [comment]
FYI - If you want to add decimal part, a possible approach is using either # or * to set as decimal point key press, and divide each number pressed after that 1/10, 1/100.. , and add it all to get the final input in decimal form.
